import type { WcagCriterion } from '@/@types/criteria';

export const WCAG_CRITERIA: WcagCriterion[] = [
  // Principle 1: Perceivable
  // Guideline 1.1: Text Alternatives
  {
    id: '1.1.1',
    name: 'Non-text Content',
    level: 'A',
    principle: 1,
    guideline: '1.1',
    description:
      'All non-text content that is presented to the user has a text alternative that serves the equivalent purpose.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html',
  },

  // Guideline 1.2: Time-based Media
  {
    id: '1.2.1',
    name: 'Audio-only and Video-only (Prerecorded)',
    level: 'A',
    principle: 1,
    guideline: '1.2',
    description: 'For prerecorded audio-only and prerecorded video-only media, alternatives are provided.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-only-and-video-only-prerecorded.html',
  },
  {
    id: '1.2.2',
    name: 'Captions (Prerecorded)',
    level: 'A',
    principle: 1,
    guideline: '1.2',
    description: 'Captions are provided for all prerecorded audio content in synchronized media.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded.html',
  },
  {
    id: '1.2.3',
    name: 'Audio Description or Media Alternative (Prerecorded)',
    level: 'A',
    principle: 1,
    guideline: '1.2',
    description:
      'An alternative for time-based media or audio description of the prerecorded video content is provided.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-description-or-media-alternative-prerecorded.html',
  },
  {
    id: '1.2.4',
    name: 'Captions (Live)',
    level: 'AA',
    principle: 1,
    guideline: '1.2',
    description: 'Captions are provided for all live audio content in synchronized media.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/captions-live.html',
  },
  {
    id: '1.2.5',
    name: 'Audio Description (Prerecorded)',
    level: 'AA',
    principle: 1,
    guideline: '1.2',
    description: 'Audio description is provided for all prerecorded video content in synchronized media.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-description-prerecorded.html',
  },
  {
    id: '1.2.6',
    name: 'Sign Language (Prerecorded)',
    level: 'AAA',
    principle: 1,
    guideline: '1.2',
    description: 'Sign language interpretation is provided for all prerecorded audio content in synchronized media.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/sign-language-prerecorded.html',
  },
  {
    id: '1.2.7',
    name: 'Extended Audio Description (Prerecorded)',
    level: 'AAA',
    principle: 1,
    guideline: '1.2',
    description:
      'Where pauses in foreground audio are insufficient to allow audio descriptions to convey the sense of the video, extended audio description is provided.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/extended-audio-description-prerecorded.html',
  },
  {
    id: '1.2.8',
    name: 'Media Alternative (Prerecorded)',
    level: 'AAA',
    principle: 1,
    guideline: '1.2',
    description:
      'An alternative for time-based media is provided for all prerecorded synchronized media and for all prerecorded video-only media.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/media-alternative-prerecorded.html',
  },
  {
    id: '1.2.9',
    name: 'Audio-only (Live)',
    level: 'AAA',
    principle: 1,
    guideline: '1.2',
    description:
      'An alternative for time-based media that presents equivalent information for live audio-only content is provided.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-only-live.html',
  },

  // Guideline 1.3: Adaptable
  {
    id: '1.3.1',
    name: 'Info and Relationships',
    level: 'A',
    principle: 1,
    guideline: '1.3',
    description:
      'Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html',
  },
  {
    id: '1.3.2',
    name: 'Meaningful Sequence',
    level: 'A',
    principle: 1,
    guideline: '1.3',
    description:
      'When the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence.html',
  },
  {
    id: '1.3.3',
    name: 'Sensory Characteristics',
    level: 'A',
    principle: 1,
    guideline: '1.3',
    description:
      'Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/sensory-characteristics.html',
  },
  {
    id: '1.3.4',
    name: 'Orientation',
    level: 'AA',
    principle: 1,
    guideline: '1.3',
    description:
      'Content does not restrict its view and operation to a single display orientation unless a specific display orientation is essential.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/orientation.html',
  },
  {
    id: '1.3.5',
    name: 'Identify Input Purpose',
    level: 'AA',
    principle: 1,
    guideline: '1.3',
    description:
      'The purpose of each input field collecting information about the user can be programmatically determined.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html',
  },
  {
    id: '1.3.6',
    name: 'Identify Purpose',
    level: 'AAA',
    principle: 1,
    guideline: '1.3',
    description:
      'In content implemented using markup languages, the purpose of User Interface Components, icons, and regions can be programmatically determined.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/identify-purpose.html',
  },

  // Guideline 1.4: Distinguishable
  {
    id: '1.4.1',
    name: 'Use of Color',
    level: 'A',
    principle: 1,
    guideline: '1.4',
    description: 'Color is not used as the only visual means of conveying information.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html',
  },
  {
    id: '1.4.2',
    name: 'Audio Control',
    level: 'A',
    principle: 1,
    guideline: '1.4',
    description:
      'If any audio on a Web page plays automatically for more than 3 seconds, either a mechanism is available to pause or stop the audio.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/audio-control.html',
  },
  {
    id: '1.4.3',
    name: 'Contrast (Minimum)',
    level: 'AA',
    principle: 1,
    guideline: '1.4',
    description: 'The visual presentation of text and images of text has a contrast ratio of at least 4.5:1.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html',
  },
  {
    id: '1.4.4',
    name: 'Resize Text',
    level: 'AA',
    principle: 1,
    guideline: '1.4',
    description:
      'Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html',
  },
  {
    id: '1.4.5',
    name: 'Images of Text',
    level: 'AA',
    principle: 1,
    guideline: '1.4',
    description:
      'If the technologies being used can achieve the visual presentation, text is used to convey information rather than images of text.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/images-of-text.html',
  },
  {
    id: '1.4.6',
    name: 'Contrast (Enhanced)',
    level: 'AAA',
    principle: 1,
    guideline: '1.4',
    description: 'The visual presentation of text and images of text has a contrast ratio of at least 7:1.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-enhanced.html',
  },
  {
    id: '1.4.7',
    name: 'Low or No Background Audio',
    level: 'AAA',
    principle: 1,
    guideline: '1.4',
    description:
      'For prerecorded audio-only content that contains primarily speech, background sounds are sufficiently low.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/low-or-no-background-audio.html',
  },
  {
    id: '1.4.8',
    name: 'Visual Presentation',
    level: 'AAA',
    principle: 1,
    guideline: '1.4',
    description:
      'For the visual presentation of blocks of text, a mechanism is available to achieve specific requirements.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/visual-presentation.html',
  },
  {
    id: '1.4.9',
    name: 'Images of Text (No Exception)',
    level: 'AAA',
    principle: 1,
    guideline: '1.4',
    description:
      'Images of text are only used for pure decoration or where a particular presentation of text is essential.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/images-of-text-no-exception.html',
  },
  {
    id: '1.4.10',
    name: 'Reflow',
    level: 'AA',
    principle: 1,
    guideline: '1.4',
    description:
      'Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/reflow.html',
  },
  {
    id: '1.4.11',
    name: 'Non-text Contrast',
    level: 'AA',
    principle: 1,
    guideline: '1.4',
    description:
      'The visual presentation of UI components and graphical objects have a contrast ratio of at least 3:1 against adjacent colors.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html',
  },
  {
    id: '1.4.12',
    name: 'Text Spacing',
    level: 'AA',
    principle: 1,
    guideline: '1.4',
    description: 'No loss of content or functionality occurs when users override text spacing properties.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/text-spacing.html',
  },
  {
    id: '1.4.13',
    name: 'Content on Hover or Focus',
    level: 'AA',
    principle: 1,
    guideline: '1.4',
    description:
      'Where receiving and then removing pointer hover or keyboard focus triggers additional content, specific conditions are met.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus.html',
  },

  // Principle 2: Operable
  // Guideline 2.1: Keyboard Accessible
  {
    id: '2.1.1',
    name: 'Keyboard',
    level: 'A',
    principle: 2,
    guideline: '2.1',
    description: 'All functionality of the content is operable through a keyboard interface.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html',
  },
  {
    id: '2.1.2',
    name: 'No Keyboard Trap',
    level: 'A',
    principle: 2,
    guideline: '2.1',
    description:
      'If keyboard focus can be moved to a component using a keyboard interface, then focus can be moved away using only a keyboard interface.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/no-keyboard-trap.html',
  },
  {
    id: '2.1.3',
    name: 'Keyboard (No Exception)',
    level: 'AAA',
    principle: 2,
    guideline: '2.1',
    description:
      'All functionality of the content is operable through a keyboard interface without requiring specific timings.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/keyboard-no-exception.html',
  },
  {
    id: '2.1.4',
    name: 'Character Key Shortcuts',
    level: 'A',
    principle: 2,
    guideline: '2.1',
    description:
      'If a keyboard shortcut is implemented using only letter, punctuation, number, or symbol characters, a mechanism is available to turn it off or remap it.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/character-key-shortcuts.html',
  },

  // Guideline 2.2: Enough Time
  {
    id: '2.2.1',
    name: 'Timing Adjustable',
    level: 'A',
    principle: 2,
    guideline: '2.2',
    description: 'For each time limit that is set by the content, specific conditions are met.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/timing-adjustable.html',
  },
  {
    id: '2.2.2',
    name: 'Pause, Stop, Hide',
    level: 'A',
    principle: 2,
    guideline: '2.2',
    description: 'For moving, blinking, scrolling, or auto-updating information, specific conditions are met.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/pause-stop-hide.html',
  },
  {
    id: '2.2.3',
    name: 'No Timing',
    level: 'AAA',
    principle: 2,
    guideline: '2.2',
    description: 'Timing is not an essential part of the event or activity presented by the content.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/no-timing.html',
  },
  {
    id: '2.2.4',
    name: 'Interruptions',
    level: 'AAA',
    principle: 2,
    guideline: '2.2',
    description: 'Interruptions can be postponed or suppressed by the user.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/interruptions.html',
  },
  {
    id: '2.2.5',
    name: 'Re-authenticating',
    level: 'AAA',
    principle: 2,
    guideline: '2.2',
    description:
      'When an authenticated session expires, the user can continue the activity without loss of data after re-authenticating.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/re-authenticating.html',
  },
  {
    id: '2.2.6',
    name: 'Timeouts',
    level: 'AAA',
    principle: 2,
    guideline: '2.2',
    description: 'Users are warned of the duration of any user inactivity that could cause data loss.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/timeouts.html',
  },

  // Guideline 2.3: Seizures and Physical Reactions
  {
    id: '2.3.1',
    name: 'Three Flashes or Below Threshold',
    level: 'A',
    principle: 2,
    guideline: '2.3',
    description: 'Web pages do not contain anything that flashes more than three times in any one second period.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold.html',
  },
  {
    id: '2.3.2',
    name: 'Three Flashes',
    level: 'AAA',
    principle: 2,
    guideline: '2.3',
    description: 'Web pages do not contain anything that flashes more than three times in any one second period.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/three-flashes.html',
  },
  {
    id: '2.3.3',
    name: 'Animation from Interactions',
    level: 'AAA',
    principle: 2,
    guideline: '2.3',
    description: 'Motion animation triggered by interaction can be disabled, unless the animation is essential.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html',
  },

  // Guideline 2.4: Navigable
  {
    id: '2.4.1',
    name: 'Bypass Blocks',
    level: 'A',
    principle: 2,
    guideline: '2.4',
    description: 'A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html',
  },
  {
    id: '2.4.2',
    name: 'Page Titled',
    level: 'A',
    principle: 2,
    guideline: '2.4',
    description: 'Web pages have titles that describe topic or purpose.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html',
  },
  {
    id: '2.4.3',
    name: 'Focus Order',
    level: 'A',
    principle: 2,
    guideline: '2.4',
    description:
      'If a Web page can be navigated sequentially, focusable components receive focus in an order that preserves meaning and operability.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html',
  },
  {
    id: '2.4.4',
    name: 'Link Purpose (In Context)',
    level: 'A',
    principle: 2,
    guideline: '2.4',
    description:
      'The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html',
  },
  {
    id: '2.4.5',
    name: 'Multiple Ways',
    level: 'AA',
    principle: 2,
    guideline: '2.4',
    description: 'More than one way is available to locate a Web page within a set of Web pages.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/multiple-ways.html',
  },
  {
    id: '2.4.6',
    name: 'Headings and Labels',
    level: 'AA',
    principle: 2,
    guideline: '2.4',
    description: 'Headings and labels describe topic or purpose.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels.html',
  },
  {
    id: '2.4.7',
    name: 'Focus Visible',
    level: 'AA',
    principle: 2,
    guideline: '2.4',
    description:
      'Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html',
  },
  {
    id: '2.4.8',
    name: 'Location',
    level: 'AAA',
    principle: 2,
    guideline: '2.4',
    description: "Information about the user's location within a set of Web pages is available.",
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/location.html',
  },
  {
    id: '2.4.9',
    name: 'Link Purpose (Link Only)',
    level: 'AAA',
    principle: 2,
    guideline: '2.4',
    description: 'A mechanism is available to allow the purpose of each link to be identified from link text alone.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-link-only.html',
  },
  {
    id: '2.4.10',
    name: 'Section Headings',
    level: 'AAA',
    principle: 2,
    guideline: '2.4',
    description: 'Section headings are used to organize the content.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/section-headings.html',
  },
  {
    id: '2.4.11',
    name: 'Focus Not Obscured (Minimum)',
    level: 'AA',
    principle: 2,
    guideline: '2.4',
    description:
      'When a user interface component receives keyboard focus, the component is not entirely hidden due to author-created content.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html',
  },
  {
    id: '2.4.12',
    name: 'Focus Not Obscured (Enhanced)',
    level: 'AAA',
    principle: 2,
    guideline: '2.4',
    description:
      'When a user interface component receives keyboard focus, no part of the component is hidden by author-created content.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-enhanced.html',
  },
  {
    id: '2.4.13',
    name: 'Focus Appearance',
    level: 'AAA',
    principle: 2,
    guideline: '2.4',
    description: 'When the keyboard focus indicator is visible, the focus indicator area meets specific requirements.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html',
  },

  // Guideline 2.5: Input Modalities
  {
    id: '2.5.1',
    name: 'Pointer Gestures',
    level: 'A',
    principle: 2,
    guideline: '2.5',
    description: 'All functionality that uses multipoint or path-based gestures can be operated with a single pointer.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/pointer-gestures.html',
  },
  {
    id: '2.5.2',
    name: 'Pointer Cancellation',
    level: 'A',
    principle: 2,
    guideline: '2.5',
    description: 'For functionality that can be operated using a single pointer, specific conditions are met.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/pointer-cancellation.html',
  },
  {
    id: '2.5.3',
    name: 'Label in Name',
    level: 'A',
    principle: 2,
    guideline: '2.5',
    description:
      'For user interface components with labels that include text or images of text, the name contains the text that is presented visually.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html',
  },
  {
    id: '2.5.4',
    name: 'Motion Actuation',
    level: 'A',
    principle: 2,
    guideline: '2.5',
    description:
      'Functionality that can be operated by device motion or user motion can also be operated by user interface components.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/motion-actuation.html',
  },
  {
    id: '2.5.5',
    name: 'Target Size (Enhanced)',
    level: 'AAA',
    principle: 2,
    guideline: '2.5',
    description: 'The size of the target for pointer inputs is at least 44 by 44 CSS pixels.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html',
  },
  {
    id: '2.5.6',
    name: 'Concurrent Input Mechanisms',
    level: 'AAA',
    principle: 2,
    guideline: '2.5',
    description: 'Web content does not restrict use of input modalities available on a platform.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/concurrent-input-mechanisms.html',
  },
  {
    id: '2.5.7',
    name: 'Dragging Movements',
    level: 'AA',
    principle: 2,
    guideline: '2.5',
    description:
      'All functionality that uses a dragging movement for operation can be achieved by a single pointer without dragging.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html',
  },
  {
    id: '2.5.8',
    name: 'Target Size (Minimum)',
    level: 'AA',
    principle: 2,
    guideline: '2.5',
    description: 'The size of the target for pointer inputs is at least 24 by 24 CSS pixels.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html',
  },

  // Principle 3: Understandable
  // Guideline 3.1: Readable
  {
    id: '3.1.1',
    name: 'Language of Page',
    level: 'A',
    principle: 3,
    guideline: '3.1',
    description: 'The default human language of each Web page can be programmatically determined.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html',
  },
  {
    id: '3.1.2',
    name: 'Language of Parts',
    level: 'AA',
    principle: 3,
    guideline: '3.1',
    description: 'The human language of each passage or phrase in the content can be programmatically determined.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-parts.html',
  },
  {
    id: '3.1.3',
    name: 'Unusual Words',
    level: 'AAA',
    principle: 3,
    guideline: '3.1',
    description:
      'A mechanism is available for identifying specific definitions of words or phrases used in an unusual or restricted way.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/unusual-words.html',
  },
  {
    id: '3.1.4',
    name: 'Abbreviations',
    level: 'AAA',
    principle: 3,
    guideline: '3.1',
    description: 'A mechanism for identifying the expanded form or meaning of abbreviations is available.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/abbreviations.html',
  },
  {
    id: '3.1.5',
    name: 'Reading Level',
    level: 'AAA',
    principle: 3,
    guideline: '3.1',
    description:
      'When text requires more than a lower secondary education reading level, supplemental content is available.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/reading-level.html',
  },
  {
    id: '3.1.6',
    name: 'Pronunciation',
    level: 'AAA',
    principle: 3,
    guideline: '3.1',
    description: 'A mechanism is available for identifying specific pronunciation of words where meaning is ambiguous.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/pronunciation.html',
  },

  // Guideline 3.2: Predictable
  {
    id: '3.2.1',
    name: 'On Focus',
    level: 'A',
    principle: 3,
    guideline: '3.2',
    description: 'When any user interface component receives focus, it does not initiate a change of context.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/on-focus.html',
  },
  {
    id: '3.2.2',
    name: 'On Input',
    level: 'A',
    principle: 3,
    guideline: '3.2',
    description:
      'Changing the setting of any user interface component does not automatically cause a change of context unless the user has been advised.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/on-input.html',
  },
  {
    id: '3.2.3',
    name: 'Consistent Navigation',
    level: 'AA',
    principle: 3,
    guideline: '3.2',
    description: 'Navigational mechanisms that are repeated on multiple Web pages occur in the same relative order.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-navigation.html',
  },
  {
    id: '3.2.4',
    name: 'Consistent Identification',
    level: 'AA',
    principle: 3,
    guideline: '3.2',
    description: 'Components that have the same functionality within a set of Web pages are identified consistently.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-identification.html',
  },
  {
    id: '3.2.5',
    name: 'Change on Request',
    level: 'AAA',
    principle: 3,
    guideline: '3.2',
    description:
      'Changes of context are initiated only by user request or a mechanism is available to turn off such changes.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/change-on-request.html',
  },
  {
    id: '3.2.6',
    name: 'Consistent Help',
    level: 'A',
    principle: 3,
    guideline: '3.2',
    description: 'If a Web page contains help mechanisms, they occur in the same relative order.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html',
  },

  // Guideline 3.3: Input Assistance
  {
    id: '3.3.1',
    name: 'Error Identification',
    level: 'A',
    principle: 3,
    guideline: '3.3',
    description:
      'If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html',
  },
  {
    id: '3.3.2',
    name: 'Labels or Instructions',
    level: 'A',
    principle: 3,
    guideline: '3.3',
    description: 'Labels or instructions are provided when content requires user input.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html',
  },
  {
    id: '3.3.3',
    name: 'Error Suggestion',
    level: 'AA',
    principle: 3,
    guideline: '3.3',
    description:
      'If an input error is automatically detected and suggestions are known, then the suggestions are provided to the user.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion.html',
  },
  {
    id: '3.3.4',
    name: 'Error Prevention (Legal, Financial, Data)',
    level: 'AA',
    principle: 3,
    guideline: '3.3',
    description:
      'For Web pages that cause legal commitments or financial transactions, submissions are reversible, checked, or confirmed.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-legal-financial-data.html',
  },
  {
    id: '3.3.5',
    name: 'Help',
    level: 'AAA',
    principle: 3,
    guideline: '3.3',
    description: 'Context-sensitive help is available.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/help.html',
  },
  {
    id: '3.3.6',
    name: 'Error Prevention (All)',
    level: 'AAA',
    principle: 3,
    guideline: '3.3',
    description:
      'For Web pages that require the user to submit information, submissions are reversible, checked, or confirmed.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-all.html',
  },
  {
    id: '3.3.7',
    name: 'Redundant Entry',
    level: 'A',
    principle: 3,
    guideline: '3.3',
    description:
      'Information previously entered by or provided to the user that is required to be entered again is auto-populated or available for the user to select.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html',
  },
  {
    id: '3.3.8',
    name: 'Accessible Authentication (Minimum)',
    level: 'AA',
    principle: 3,
    guideline: '3.3',
    description:
      'A cognitive function test is not required for any step in an authentication process unless specific conditions are met.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html',
  },
  {
    id: '3.3.9',
    name: 'Accessible Authentication (Enhanced)',
    level: 'AAA',
    principle: 3,
    guideline: '3.3',
    description: 'A cognitive function test is not required for any step in an authentication process.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced.html',
  },

  // Principle 4: Robust
  // Guideline 4.1: Compatible
  {
    id: '4.1.2',
    name: 'Name, Role, Value',
    level: 'A',
    principle: 4,
    guideline: '4.1',
    description: 'For all user interface components, the name and role can be programmatically determined.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html',
  },
  {
    id: '4.1.3',
    name: 'Status Messages',
    level: 'AA',
    principle: 4,
    guideline: '4.1',
    description:
      'In content implemented using markup languages, status messages can be programmatically determined through role or properties.',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html',
  },
];

export const PRINCIPLE_NAMES: Record<number, string> = {
  1: 'Perceivable',
  2: 'Operable',
  3: 'Understandable',
  4: 'Robust',
};
